services:
  strapi:
    image: k3n5h1n/strapi-blog:latest
    container_name: my-strapi-project
    restart: unless-stopped
    env_file:
      - ./my-strapi-project/.env
    environment:
      - HOST=0.0.0.0
      - PORT=1337
      - NODE_ENV=production
      - DATABASE_CLIENT=sqlite
      - DATABASE_FILENAME=.tmp/data.db
    ports:
      - "1337:1337"
    volumes:
      - ./my-strapi-project/.tmp:/opt/app/.tmp
      - ./my-strapi-project/public/uploads:/opt/app/public/uploads
    networks:
      - strapi-network

networks:
  strapi-network:
    driver: bridge
